config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cessda/cessda.cdc.searchkit:
      branch: main
      repo: https://github.com/cessda/cessda.cdc.searchkit.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-alizarin-loon.sh
        container: qc.acc_chewy-sepia-whale
  QC.Doc:
    repos:
      github.com/cessda/cessda.cdc.searchkit find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-seashell-capybara.sh
        container: qc.doc_hilly-lavender-ray
      github.com/cessda/cessda.cdc.searchkit git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-eggplant-sheepdog.sh
        container: qc.doc_flabby-lilac-lion
      github.com/cessda/cessda.cdc.searchkit markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-red-dolphin.sh
        container: qc.doc_sleepy-smalt-chinchilla
  QC.Lic:
    repos:
      github.com/cessda/cessda.cdc.searchkit licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-gamboge-weasel.sh
        container: qc.lic_baggy-seashell-dollar
  QC.Met:
    repos:
      github.com/cessda/cessda.cdc.searchkit cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-eggplant-tiger.sh
        container: qc.met_dorky-red-opossum
  QC.Sty:
    repos:
      github.com/cessda/cessda.cdc.searchkit hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-aqua-barb.sh
        container: qc.sty_nerdy-cream-bullfrog
      github.com/cessda/cessda.cdc.searchkit jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-black-catfish.sh
        container: qc.sty_sloppy-carmine-shark
  QC.Ver:
    repos:
      github.com/cessda/cessda.cdc.searchkit get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-fuchsia-ferret.sh
        container: qc.ver_gimpy-amber-rat
timeout: 5400
